apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: aimmo-ingress
  annotations:
    ingress.kubernetes.io/enable-cors: "true"
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: dev.aimmo.codeforlife.education
      http:
        paths:
            - backend:
                serviceName: default-http-backend
                servicePort: 80
